# -*- coding: utf-8 -*-
"""DNNs Dropout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQmFcZaO_lB9xoJ0_tz1dKMEUaSHLNqW
"""

# !pip install tensorflow

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/Vechical/"

import tensorflow as tf

IMG_HEIGHT = 224
IMG_WIDTH = 224
IMG_CHANNELS = 3

# Corrected CLASS_NAMES to match the actual directory names
CLASS_NAMES = ['Bike', 'Car']

def read_and_decode(filename, resize_dims):
    img_bytes = tf.io.read_file(filename)
    img = tf.image.decode_jpeg(img_bytes, channels=IMG_CHANNELS)
    img = tf.squeeze(img)
    img.set_shape([None, None, IMG_CHANNELS])
    img = tf.image.convert_image_dtype(img, tf.float32)
    img = tf.image.resize(img, resize_dims)
    return imgg

def parse_csvline(csv_line):
    record_default = ["", ""]
    filename, label_string = tf.io.decode_csv(csv_line, record_default)

    img = read_and_decode(filename, [IMG_HEIGHT, IMG_WIDTH])

    label = tf.argmax(tf.math.equal(CLASS_NAMES, label_string))
    return img, label

import tensorflow as tf
import pathlib


# Path to your uploaded dataset
data_dir = pathlib.Path(r"/content/drive/MyDrive/Vechical/")

# Count JPG images
image_count = len(list(data_dir.glob('*/*.jpg')))

print("Images found:", image_count)
print("data_dir:", data_dir)

import random
import math
CLASS_NAMES = ['Bike','Car']
random.seed(42)

TRAIN_CSV = '/tmp/train_set.csv'
EVAL_CSV  = '/tmp/eval_set.csv'

train_rows, eval_rows = [], []

for cls in CLASS_NAMES:
    cls_dir = data_dir / cls
    images  = sorted(str(p) for p in cls_dir.glob('*.jpg'))
    random.shuffle(images)
    split = math.ceil(len(images) * 0.8)
    train_rows += [(p, cls) for p in images[:split]]
    eval_rows  += [(p, cls) for p in images[split:]]

random.shuffle(train_rows)
random.shuffle(eval_rows)

with open(TRAIN_CSV, 'w') as f:
    for path, label in train_rows:
        f.write(f'{path},{label}\n')

with open(EVAL_CSV, 'w') as f:
    for path, label in eval_rows:
        f.write(f'{path},{label}\n')

print(f'Train samples : {len(train_rows)}')
print(f'Eval  samples : {len(eval_rows)}')

def read_and_decode(filename,resize_dims):
  img_bytes =tf.io.read_file(filename)
  img=tf.image.decode_jpeg(img_bytes,channels=IMG_CHANNELS)
  # Ensure the image is 3-dimensional by removing any singleton dimensions
  img = tf.squeeze(img)
  # Explicitly reshape to ensure it's always 3D ([height, width, channels])
  # This handles cases where tf.squeeze might not fully reduce rank due to unusual image encoding
  img = tf.reshape(img, (tf.shape(img)[-3], tf.shape(img)[-2], tf.shape(img)[-1]))
  img=tf.image.convert_image_dtype(img,tf.float32)
  img=tf.image.resize(img,resize_dims)
  return img

def parse_csvline(csv_line):

    record_default = ["", ""]
    filename, label_string = tf.io.decode_csv(csv_line, record_default)

    img = read_and_decode(filename, [IMG_HEIGHT, IMG_WIDTH])


    label = tf.argmax(tf.math.equal(CLASS_NAMES, label_string))
    return img, label

train_dataset = (
    tf.data.TextLineDataset(TRAIN_CSV)
    .map(parse_csvline, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(16)
    .prefetch(tf.data.AUTOTUNE)
)

eval_dataset = (
    tf.data.TextLineDataset(EVAL_CSV)
    .map(parse_csvline, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(16)
    .prefetch(tf.data.AUTOTUNE)
)

print('Datasets ready.')

for image_batch, label_batch in train_dataset.take(0):
    print("Image batch shape:", image_batch.shape)
    print("Label batch shape:", label_batch.shape)
    print("Labels:", label_batch.numpy())

import matplotlib.pyplot as plt

for image_batch, label_batch in train_dataset.take(2):
    # Take the first image from the batch
    first_image = image_batch[0]
    first_label = label_batch[0]

    # Convert tensor to numpy array
    plt.imshow(first_image.numpy())
    plt.title(f"Label: {CLASS_NAMES[first_label]}")
    plt.axis('off')
    plt.show()

import matplotlib.pyplot as plt

# Take one batch from the dataset
for image_batch, label_batch in train_dataset.take(2):
    fig, axes = plt.subplots(4, 4, figsize=(10, 10))  # Create a 4x4 grid

    for i in range(16):  # Loop over the first 16 images
        ax = axes[i // 4, i % 4]  # Determine grid position
        ax.imshow(image_batch[i].numpy())  # Convert tensor to numpy array
        ax.set_title(f"Label: {CLASS_NAMES[label_batch[i]]}")
        ax.axis("off")  # Hide axes

    plt.tight_layout()
    plt.show()

model = keras.Sequential([
    keras.Input(shape=(IMG_HEIGHT,IMG_WIDTH,IMG_CHANNELS)),
    keras.layers.Flatten(),
    keras.layers.Dense(128 ,activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(len(CLASS_NAMES),activation='softmax')
])

model.compile(
    optimizer="adam",
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=["accuracy"]
)

EPOCHS = 10

history = model.fit(
    train_dataset,
    validation_data=eval_dataset,
    epochs=EPOCHS
)

import matplotlib.pyplot as plt

plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import math

for images, labels in eval_dataset.take(1):
    batch_predictions = model.predict(images)
    predicted_indices = np.argmax(batch_predictions, axis=1)


    num_images = images.shape[0]


    num_cols = 4
    num_rows = math.ceil(num_images / num_cols)


    plt.figure(figsize=(12, 3 * num_rows))

    for i in range(num_images):
        plt.subplot(num_rows, num_cols, i + 1)


        plt.imshow(images[i].numpy())
        plt.axis('off')


        pred_class = CLASS_NAMES[predicted_indices[i]]
        actual_class = CLASS_NAMES[labels[i].numpy()]


        plt.title(f"Pred: {pred_class}\nActual: {actual_class}", fontsize=10)


    plt.tight_layout()
    plt.show()